-- TABLES

CREATE TABLE car_option
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key       VARCHAR(255) NOT NULL UNIQUE,
    level     INTEGER      NOT NULL,
    name      VARCHAR(255) NOT NULL,
    parent_id BIGINT,
    CONSTRAINT fk_car_option_parent FOREIGN KEY (parent_id) REFERENCES car_option (id)
);

CREATE TABLE submission
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    has_license BOOLEAN      NOT NULL,
    name        VARCHAR(255) NOT NULL,
    phone       VARCHAR(255) NOT NULL
);

CREATE TABLE submission_car_option
(
    submission_id BIGINT NOT NULL,
    car_option_id BIGINT NOT NULL,
    PRIMARY KEY (submission_id, car_option_id),
    CONSTRAINT fk_submission FOREIGN KEY (submission_id) REFERENCES submission (id),
    CONSTRAINT fk_car_option FOREIGN KEY (car_option_id) REFERENCES car_option (id)
);

-- INITIAL DATA (ONLY car_option)

INSERT INTO car_option (id, key, level, name, parent_id)
VALUES (1, 'mercedes', 0, 'Mercedes-Benz', NULL),
       (2, 'mercedes_c', 1, 'C klass', 1),
       (3, 'mercedes_c160', 2, 'C 160', 2),
       (4, 'mercedes_c180', 2, 'C 180', 2),
       (5, 'mercedes_c200', 2, 'C 200', 2),
       (6, 'mercedes_c220', 2, 'C 220', 2),

       (7, 'bmw', 0, 'BMW', NULL),
       (8, 'bmw_3', 1, '3 seeria', 7),
       (9, 'bmw_315', 2, '315', 8),
       (10, 'bmw_316', 2, '316', 8),
       (11, 'bmw_317', 2, '317', 8),
       (12, 'bmw_318', 2, '318', 8),
       (13, 'bmw_319', 2, '319', 8),
       (14, 'bmw_4', 1, '4 seeria', 7),
       (15, 'bmw_5', 1, '5 seeria', 7),
       (16, 'bmw_518', 2, '518', 15),
       (17, 'bmw_520', 2, '520', 15),
       (18, 'bmw_523', 2, '523', 15),
       (19, 'bmw_524', 2, '524', 15),
       (20, 'bmw_525', 2, '525', 15),

       (21, 'audi', 0, 'Audi', NULL),
       (22, 'audi_a', 1, 'A seeria', 21),
       (23, 'audi_etron', 1, 'e-tron', 21),
       (24, 'audi_q', 1, 'Q seeria', 21),
       (25, 'audi_q2', 2, 'Q2', 24),
       (26, 'audi_q3', 2, 'Q3', 24),
       (27, 'audi_q4', 2, 'Q4', 24),
       (28, 'audi_q5', 2, 'Q5', 24),
       (29, 'audi_q7', 2, 'Q7', 24),
       (30, 'audi_rs', 1, 'RS seeria', 21),
       (31, 'audi_rs4', 2, 'RS4', 30),
       (32, 'audi_rs5', 2, 'RS5', 30),
       (33, 'audi_rs6', 2, 'RS6', 30),
       (34, 'audi_tt', 1, 'TT', 21),

       (35, 'citroen', 0, 'Citroën', NULL),
       (36, 'muu', 0, 'Muu', NULL);